### PR TITLE
Static shorthand function to match a version with a range expression.

### PR DESCRIPTION
**Pull request by vicary**
Regarding #49

### CODE REVIEW

**Comment by vierbergenlars** [comment]
Thank you!

**Comment by vicary** [comment]
Sorry I made a typo and fixed that in 2df0fa88a1cf4eacb3278ece299b3cea5b6cbbdc, should I make another PR?

**Comment by vierbergenlars** [comment]
No problem, I applied your patch myself in 08d45a3, so you don't have to make a PR for that.
Actually it's my mistake, I should have looked at the code more closely before merging

**Comment by vicary** [comment]
Nice :smile:

**Pull request merged**
