### PR TITLE
Rename Object to JObject for php7 compliance

### PR DESCRIPTION
**Pull request by brunolorentin-booxmedia**
fix for

src/vierbergenlars/LibJs/Object.php

reservedNames
Line 26: class Object

### CODE REVIEW

**Comment by garak** [comment]
Any news on this? This problem is preventing my lib to be tested on php 7.2

**Comment by vierbergenlars** [comment]
Ah yes, I missed this one because there were failing tests, but it seems that was due to a Travis glitch.

**Comment by garak** [comment]
What about releasing 3.0.2?

**Comment by vierbergenlars** [comment]
Yes, I made a new release to fix this.

**Pull request merged**
